version: '3.8'
services: 
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: club_backend_prod
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: prod.env
  fullstack:
    build: .
    env_file: prod.env
    ports: 
      - 4000:80
# Define the volumes
volumes:
  dbdata:
